linters-settings:
  govet:
    check-shadowing: true
  misspell:
    locale: US

linters:
  enable-all: true
  disable:
    - wsl
    - funlen
    - godox
    # - lll
    - maligned
    - paralleltest

linters-settings:
  errcheck:
    # report about not checking of errors in type assertions: `a := b.(MyStruct)`;
    # default is false: such cases aren't reported by default.
    check-type-assertions: false

    # report about assignment of errors to blank identifier: `num, _ := strconv.Atoi(numStr)`;
    # default is false: such cases aren't reported by default.
    check-blank: false

    # [deprecated] comma-separated list of pairs of the form pkg:regex
    # the regex is used to ignore names within pkg. (default "fmt:.*").
    # see https://github.com/kisielk/errcheck#the-deprecated-method for details
    ignore: fmt:.*,io/ioutil:^Read.*
    # ignore: fmt:Println,fmt:Print,github.com/peer-calls/peer-calls/server/logger:A

    # path to a file containing a list of functions to exclude from checking
    # see https://github.com/kisielk/errcheck#excluding-functions for details
    exclude: .golangci-errcheck-exclude.txt
  # exhaustivestruct:
  #   struct-patterns:
  #     - 'github.com/peer-calls/peer-calls/server/message.Payload'
# issues:
#   # exclude-use-default: false
#   # exclude-rules:
#   #   - path: rtptransceiverinit
#   #     text: "type RtpTransceiverInit should be RTPTransceiverInit"
#   #     linters:
#   #       - stylecheck

# run:
#   skip-dirs-use-default: false
